jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.x", "3.x", "pypy-2.7", "pypy-3.7", "pypy-3.8"]
    name: Python ${{ matrix.python-version }} sample
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    with:
    python-version: '3.9'
    cache: 'pip'
    - run: pip install -r requirements.txt